import {useEffect,useRef,useState} from 'react';
import {request} from '../services/api-client';
import {uiSocket} from '../services/socket-client';
import {useLiveQuery} from '../hooks/use-live-query';
import {currentReportYear} from '../matrix-plan';
type Daily={date:string;updatedCases:number;totalCases:number|null;remainingCases:number|null;percent:number|null;state:string;activeCases:number;failedCases:number;reviewCases:number;lastSavedAt:string|null;lastSavedCase:string|null;firstNotUpdated:{name:string;state:string;rto:string}|null};
type Dataset={datasetId:string;label:string;year:number;latest:Daily|null;days:Daily[]};
type Data={datasets:Dataset[];coverageBasis:string};
const timestamp=(value:string|null)=>value?new Date(value).toLocaleString('en-GB',{timeZone:'Asia/Ho_Chi_Minh',day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit',hour12:false}):'—';
const dateLabel=(value:string)=>value.split('-').reverse().join('/');
const statuses:Record<string,string>={complete:'Complete for known cases',updating:'Updating / queued',paused:'Paused',partial:'Partially refreshed',unknown:'Coverage unknown'};
function Coverage({row}:{row:Daily}){return <div className="update-history-coverage"><strong>{row.updatedCases.toLocaleString()} / {row.totalCases?.toLocaleString()??'?'}</strong><span>cases refreshed{row.percent!=null?` · ${row.percent}%`:''}</span>{row.percent!=null&&<progress value={row.updatedCases} max={row.totalCases||1}/>}</div>;}
function Content(){
 const current=currentReportYear();const [from,setFrom]=useState(Math.max(1900,current-3)),[to,setTo]=useState(current),[selected,setSelected]=useState('');
 const valid=from>=1900&&to>=from&&to-from<=20&&to<=9999;
 const query=useLiveQuery<Data>(JSON.stringify([from,to]),signal=>valid?request<Data>(`/api/annual-reports/update-status?fromYear=${from}&toYear=${to}`,{signal}):Promise.resolve({datasets:[],coverageBasis:''}),15000);
 useEffect(()=>{const refresh=()=>query.refresh();const timer=setInterval(refresh,15000);uiSocket.on('reports:updated',refresh);uiSocket.on('job:status',refresh);uiSocket.on('connect',refresh);return()=>{clearInterval(timer);uiSocket.off('reports:updated',refresh);uiSocket.off('job:status',refresh);uiSocket.off('connect',refresh);};},[query.refresh]);
 const options=[...new Map(query.data?.datasets.map(item=>[item.datasetId,{id:item.datasetId,label:item.label}])||[]).values()];
 const items=query.data?.datasets.filter(item=>!selected||item.datasetId===selected)||[];
 return <><div className="update-history-controls"><label>From year<input type="number" aria-label="Update history from year" min={1900} max={9999} value={from} onChange={event=>setFrom(Number(event.target.value))}/></label><label>To year<input type="number" aria-label="Update history to year" min={from} max={9999} value={to} onChange={event=>setTo(Number(event.target.value))}/></label><label>Dataset<select aria-label="Update history dataset" value={selected} onChange={event=>setSelected(event.target.value)}><option value="">All datasets</option>{options.map(item=><option key={item.id} value={item.id}>{item.label}</option>)}</select></label><button type="button" onClick={()=>query.refresh(true)} disabled={!valid}>Refresh</button></div>
 {!valid&&<p role="alert">Choose an ordered year range of at most 21 years.</p>}{query.error&&<p role="alert">{query.error}</p>}{query.loading&&<p role="status">Updating history…</p>}
 <p className="update-history-note">Dates and times: GMT+7. Coverage uses recorded case plans. A recent save on some RTOs does not mean the entire dataset is current. Confirmed no-data cases count as refreshed; failed or review cases do not.</p>
 {!query.loading&&!items.length&&<p>No update records in this year range.</p>}
 <div className="update-history-table-wrap"><table className="update-history-table"><thead><tr><th>Dataset / year</th><th>Latest activity day</th><th>Daily coverage</th><th>Status</th><th>Update position</th><th>History by day</th></tr></thead><tbody>{items.map(item=>item.latest&&<tr key={`${item.datasetId}-${item.year}`}><td><strong>{item.year}</strong><span>{item.label}</span></td><td>{dateLabel(item.latest.date)}</td><td><Coverage row={item.latest}/></td><td><span className="update-history-status" data-state={item.latest.state}>{statuses[item.latest.state]}</span><small>{item.latest.remainingCases!=null?`${item.latest.remainingCases} cases not refreshed on this day`:'No full case plan recorded'}</small>{item.latest.activeCases>0&&<small>{item.latest.activeCases} processing / queued</small>}{item.latest.failedCases>0&&<small>{item.latest.failedCases} failed</small>}{item.latest.reviewCases>0&&<small>{item.latest.reviewCases} imports need review</small>}</td><td><span>Last save: {timestamp(item.latest.lastSavedAt)}</span>{item.latest.lastSavedCase&&<small title={item.latest.lastSavedCase}>{item.latest.lastSavedCase}</small>}{item.latest.firstNotUpdated&&<><b>First case not refreshed</b><small title={item.latest.firstNotUpdated.name}>{item.latest.firstNotUpdated.state} · {item.latest.firstNotUpdated.rto}</small></>}</td><td><details><summary>{item.days.length} days</summary><div className="update-history-days">{item.days.map(row=><div key={row.date}><strong>{dateLabel(row.date)}</strong><Coverage row={row}/><span>{statuses[row.state]}</span><small>Last save: {timestamp(row.lastSavedAt)}</small></div>)}</div></details></td></tr>)}</tbody></table></div>
 <p className="update-history-note">Coverage across a day can have gaps because workers run in parallel. “First case not refreshed” follows the recorded plan order. Imported data without a recorded full plan is shown as coverage unknown.</p></>;
}
export function UpdateHistory(){
 const [open,setOpen]=useState(false);const dialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{if(open&&!dialog.current?.open)dialog.current?.showModal();if(!open&&dialog.current?.open)dialog.current.close();},[open]);
 return <><button type="button" onClick={()=>setOpen(true)}>Update history</button><dialog ref={dialog} className="update-history-dialog" aria-labelledby="update-history-title" onCancel={()=>setOpen(false)} onClose={()=>setOpen(false)}><header><div><h2 id="update-history-title">Dataset update status</h2><p>Daily refresh coverage by report filters and year</p></div><button type="button" aria-label="Close update history" onClick={()=>setOpen(false)}>×</button></header><div className="update-history-body">{open&&<Content/>}</div></dialog></>;
}
